#!/usr/bin/env sh
# the scripting-addition must be loaded manually if you are running yabai on macOS Big Sur. Uncomment
# the following line to have the injection performed
# when the config is executed during startup.
#
# for this to work you must configure sudo such that
# it will be able to run the command without password
#
# see this wiki page for information:
#  - https://github.com/koekeishiya/yabai/wiki/Installing-yabai-(latest-release)
#
# sudo yabai --load-sa
# yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"

# yabai template colours
CBACK=$(echo $background | sed 's/#//')
CFORE=$(echo $foreground | sed 's/#//')
CACTV=$(echo $color3 | sed 's/#//')
CNORM=$(echo $color1 | sed 's/#//')
CINSE=$(echo $foreground | sed 's/#//')

# global settings
yabai -m config mouse_follows_focus          off
yabai -m config focus_follows_mouse          off
yabai -m config window_placement             second_child
yabai -m config window_topmost               off
yabai -m config window_shadow                on
yabai -m config window_opacity               off
yabai -m config window_opacity_duration      0.0
yabai -m config active_window_opacity        1.0
yabai -m config normal_window_opacity        0.90
yabai -m config window_border                off
yabai -m config window_border_width          4
yabai -m config active_window_border_color   0xff$CACTV
yabai -m config normal_window_border_color   0xff$CNORM
yabai -m config insert_window_border_color   0xff$CINSE
yabai -m config insert_feedback_color        0xffd75f5f
yabai -m config split_ratio                  0.50
yabai -m config auto_balance                 on
yabai -m config mouse_modifier               fn
yabai -m config mouse_action1                move
yabai -m config mouse_action2                resize
yabai -m config mouse_drop_action            swap

# application settings
yabai -m rule --add app="^System Preferences$" sticky=on layer=above manage=off
yabai -m rule --add app="^Karabiner-Elements$" sticky=on layer=above manage=off
yabai -m rule --add app="^Karabiner-EventViewer$" sticky=on layer=above manage=off
yabai -m rule --add app="^Finder$" sticky=on layer=above manage=off
yabai -m rule --add app="^Disk Utility$" sticky=on layer=above manage=off
yabai -m rule --add app="^System Information$" manage=off
yabai -m rule --add app="^Activity Monitor$" manage=off
yabai -m rule --add app="^Dictionary$" manage=off
# yabai -m rule --add app="^iTerm2$" manage=off
yabai -m rule --add app="^Flux$" manage=off
yabai -m rule --add app="^Time Out$" manage=off
yabai -m rule --add app="^Logi Options$" manage=off
# yabai -m rule --add app="^Private Internet Access$" manage=off
# yabai -m rule --add app="^Music$" sticky=on manage=off
# yabai -m rule --add app="^Spotify$" sticky=on manage=off
yabai -m rule --add app="^KakaoTalk$" sticky=on manage=off
# yabai -m rule --add app="^Discord$" sticky=on manage=off
yabai -m rule --add app="^Calendar$" manage=off
yabai -m rule --add app="^Creative Cloud$" manage=off
yabai -m rule --add app="^Adobe Photoshop 2021$" manage=off
yabai -m rule --add app="^Adobe After Effects 2021$" manage=off
yabai -m rule --add app="^Adobe Premier Pro 2021" manage=off
yabai -m rule --add app="^Adobe Illustrator 2021$" manage=off
yabai -m rule --add app="^Adobe Lightroom$" manage=off
yabai -m rule --add app="^Installer$" manage=off
yabai -m rule --add app="^Preview$" manage=off
yabai -m rule --add app="^Stocks$" manage=off
yabai -m rule --add app="^Calculator$" manage=off
yabai -m rule --add app="^Blender$" manage=off
yabai -m rule --add app="^UTM$" manage=off

# general space settings
yabai -m config layout                       bsp
yabai -m config top_padding                  0
yabai -m config bottom_padding               0
yabai -m config left_padding                 0
yabai -m config right_padding                0
yabai -m config window_gap                   0

yabai -m config status_bar_background_color  0xff$CBACK
yabai -m config status_bar_foreground_color  0xff$CFORE


echo "yabai configuration loaded.."
