#!/usr/bin/env bash

configel="$HOME/.config/doom/config.el"
colorschemeLine=$(awk "/;; Load a theme/{ print NR; exit }" $configel)
colorschemeLine=$(($colorschemeLine + 1))
# ls ~/.config/doom/themes | sed "s/-theme.el//"
color=$(printf "%s\n" $(cat $HOME/.bin/themes/doom-themes.txt) $(ls ~/.config/doom/themes | sed "s/-theme.el//") | sort | fzf --height 30% --reverse --prompt "Set doom theme as: ")
if [[ -z $color ]]; then
	exit 0;
fi

sed -i '' -e "${colorschemeLine}s/.*/(setq doom-theme '${color})/" $configel
echo 'Done editing config.el. Please do M-x doom/reload in doom and restart it'
