#!/usr/bin/env bash
projectPath=$(find $HOME/codes $HOME/.config $HOME/.bin $HOME/godot $HOME/Documents/neorg $HOME/Documents/org -type d -maxdepth 2 | fzf-tmux -p 90%)

if [[ -z $projectPath ]]; then
	exit 0
fi

projectName=$(echo $projectPath | rev | cut -d'/' -f 1 | rev)

if [[ ${projectName:0:1} == \. ]]; then
	projectName="${projectName:1}"
fi

if ! tmux has-session -t=$projectName 2> /dev/null; then
	tmux new-session -c $projectPath -ds $projectName 
fi

tmux switch-client -t $projectName
