#!/usr/bin/env bash

kittyConfFile="$HOME/.config/kitty/kitty.conf"
colorschemeLine=$(awk "/Set-Colorscheme/{ print NR; exit }" $kittyConfFile)
colorschemeLine=$(($colorschemeLine +1))
color=$(ls $HOME/.config/kitty/themes | fzf --height 30% --reverse --prompt "Set kitty theme as: ")

if [[ -z $color ]]; then
    exit 0;
fi

sed -i '' -e "${colorschemeLine}s|.*|include ./themes/${color}|" $kittyConfFile
