#!/usr/bin/env bash

session_name=$(echo $PWD | rev | cut -d "/" -f 1 | rev)

if [[ ${session_name:0:1} == \. ]]; then
	session_name="${session_name:1}"
fi

if ! tmux has-session -t=$session_name 2> /dev/null; then
	tmux new-session -c $PWD -ds $session_name 
fi

tmux switch-client -t $session_name
